"""Commands for the Mailchimp /audiences API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import json

import click


def _parse_json_option(value, option_name, require_object=False):
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError as exc:
        raise click.BadParameter(
            f"must be valid JSON ({exc.msg})",
            param_hint=option_name,
        ) from exc
    if require_object and not isinstance(parsed, dict):
        raise click.BadParameter("must be a JSON object", param_hint=option_name)
    return parsed


@click.group("audiences")
@click.pass_context
def audiences_group(ctx):
    """audiences resource commands."""

@audiences_group.command("list")
@click.argument("AUDIENCE_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--count", default=None, type=int, help="The number of records to return. Default value is 10. Maximum value is 1000")
@click.option("--cursor", default=None, help="Paginate through a collection of records by setting the `cursor` parameter to a ")
@click.option("--created-before", default=None, help="Restricts the response to contacts created at or before the specified time (incl")
@click.option("--created-since", default=None, help="Restricts the response to contacts created after the specified time (exclusive).")
@click.option("--updated-before", default=None, help="Restricts the response to contacts updated at or before the specified time (incl")
@click.option("--updated-since", default=None, help="Restricts the response to contacts updated after the specified time (exclusive).")
@click.option("--sort-field", default=None, help="Specifies the field to sort the returned contacts by.")
@click.option("--sort-dir", default=None, help="Determines the order direction for sorted results.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, audience_id, fields, exclude_fields, count, cursor, created_before, created_since, updated_before, updated_since, sort_field, sort_dir, extra_params):
    """Get Contacts"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    path = f"/audiences/{audience_id}/contacts"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
        "count": count,
        "cursor": cursor,
        "created_before": created_before,
        "created_since": created_since,
        "updated_before": updated_before,
        "updated_since": updated_since,
        "sort_field": sort_field,
        "sort_dir": sort_dir,
    }.items() if v is not None}
    if extra_params:
        params.update(_parse_json_option(extra_params, "--extra-params", require_object=True))
    client = get_client()
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@audiences_group.command("create")
@click.argument("AUDIENCE_ID")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--merge-field-validation-mode", default=None, help="Defines how merge field validation is handled. When set to `ignore_required_chec")
@click.option("--data-mode", default=None, help="Indicates the data processing mode. In `historical` mode, contact data changes d")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_create(ctx, audience_id, data, merge_field_validation_mode, data_mode, extra_params):
    """Add Contact"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    path = f"/audiences/{audience_id}/contacts"
    params = {k: v for k, v in {
        "merge_field_validation_mode": merge_field_validation_mode,
        "data_mode": data_mode,
    }.items() if v is not None}
    if extra_params:
        params.update(_parse_json_option(extra_params, "--extra-params", require_object=True))
    body = _parse_json_option(data, "--data") if data else None
    client = get_client()
    try:
        result = client.post(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@audiences_group.command("get")
@click.argument("AUDIENCE_ID")
@click.argument("CONTACT_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_get(ctx, audience_id, contact_id, fields, exclude_fields, extra_params):
    """Get Contact"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    path = f"/audiences/{audience_id}/contacts/{contact_id}"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
    }.items() if v is not None}
    if extra_params:
        params.update(_parse_json_option(extra_params, "--extra-params", require_object=True))
    client = get_client()
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@audiences_group.command("update")
@click.argument("AUDIENCE_ID")
@click.argument("CONTACT_ID")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--merge-field-validation-mode", default=None, help="Defines how merge field validation is handled. When set to `ignore_required_chec")
@click.option("--data-mode", default=None, help="Indicates the data processing mode. In `historical` mode, contact data changes d")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_update(ctx, audience_id, contact_id, data, merge_field_validation_mode, data_mode, extra_params):
    """Update Contact"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    path = f"/audiences/{audience_id}/contacts/{contact_id}"
    params = {k: v for k, v in {
        "merge_field_validation_mode": merge_field_validation_mode,
        "data_mode": data_mode,
    }.items() if v is not None}
    if extra_params:
        params.update(_parse_json_option(extra_params, "--extra-params", require_object=True))
    body = _parse_json_option(data, "--data") if data else None
    client = get_client()
    try:
        result = client.patch(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
